<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class Userdata_Seeder extends Seeder
{
    public function run(): void
    {
        DB::table('users')->insert([
            [
                'id' => 1,
                'name' => 'Admin Yuwaraja',
                'nim' => '0000000000',
                'photo' => null,
                'username' => 'admin',
                'email' => 'admin@yuwaraja.com',
                'program_studi' => 'D3 Teknologi Informasi',
                'deskripsi' => null,
                'angkatan' => 2023,
                'nomor_telepon' => '081234567890',
                'tanggal_lahir' => '1990-01-01',
                'jenis_kelamin' => 'Laki-laki',
                'role' => 'admin',
                'kelompok_id' => null,
                'password' => '1',
                'remember_token' => null,
                'email_verified_at' => '2025-07-12 17:18:40',
                'created_at' => '2025-07-12 17:18:40',
                'updated_at' => '2025-07-12 17:18:40',
            ],
            [
                'id' => 3,
                'name' => 'Wawa Ponorogo',
                'nim' => '233140707111087',
                'photo' => null,
                'username' => 'wawa',
                'email' => 'wawaponorogo@gmail.com',
                'program_studi' => 'D3 Administrasi Bisnis',
                'deskripsi' => null,
                'angkatan' => 2023,
                'nomor_telepon' => '081234567891',
                'tanggal_lahir' => '2004-02-18',
                'jenis_kelamin' => 'Perempuan',
                'role' => 'spv',
                'kelompok_id' => 1,
                'password' => '1',
                'remember_token' => null,
                'email_verified_at' => '2025-07-14 04:32:29',
                'created_at' => '2025-07-12 17:18:40',
                'updated_at' => '2025-07-14 04:32:29',
            ],
            [
                'id' => 4,
                'name' => 'Rafif Nabiha',
                'nim' => '233140707111123',
                'photo' => null,
                'username' => 'rafif',
                'email' => 'rafifnabiha24@gmail.com',
                'program_studi' => 'D3 Keuangan dan Perbankan',
                'deskripsi' => null,
                'angkatan' => 2024,
                'nomor_telepon' => '081234567892',
                'tanggal_lahir' => '2005-03-22',
                'jenis_kelamin' => 'Laki-laki',
                'role' => 'mahasiswa',
                'kelompok_id' => 1,
                'password' => '1',
                'remember_token' => null,
                'email_verified_at' => '2025-07-14 04:32:29',
                'created_at' => '2025-07-12 17:18:40',
                'updated_at' => '2025-07-14 04:32:29',
            ],
            [
                'id' => 2,
                'name' => 'Hanin Betawi',
                'nim' => '223140707111092',
                'photo' => null,
                'username' => 'hanin',
                'email' => 'haninbetawi@gmail.com',
                'program_studi' => 'D4 Manajemen Perhotelan',
                'deskripsi' => null,
                'angkatan' => 2022,
                'nomor_telepon' => '081234567893',
                'tanggal_lahir' => '2003-07-15',
                'jenis_kelamin' => 'Laki-laki',
                'role' => 'spv',
                'kelompok_id' => 2,
                'password' => '1',
                'remember_token' => null,
                'email_verified_at' => '2025-07-14 04:32:29',
                'created_at' => '2025-07-12 17:18:41',
                'updated_at' => '2025-07-14 04:32:29',
            ],
            [
                'id' => 5,
                'name' => 'Sabil Bandung',
                'nim' => '253140707111056',
                'photo' => 'profile_5_1752398389.jpeg',
                'username' => 'sabil',
                'email' => 'sblhh.m@gmail.com',
                'program_studi' => 'D4 Desain Grafis',
                'deskripsi' => 'aku suka ngoding js',
                'angkatan' => 2025,
                'nomor_telepon' => '082334567892',
                'tanggal_lahir' => '2007-05-12',
                'jenis_kelamin' => 'Laki-laki',
                'role' => 'mahasiswa',
                'kelompok_id' => 2,
                'password' => '1',
                'remember_token' => null,
                'email_verified_at' => '2025-07-14 04:32:29',
                'created_at' => '2025-07-12 17:18:41',
                'updated_at' => '2025-07-14 04:32:29',
            ],
        ]);
    }
}
